# QUESTO DOCKER-COMPOSE È USATO SOLO PER IL DEBUGGING
# In produzione, le cartelle node_modules non vengono incluse nei container

# Ciò è fattibile in development in quanto si programma già in ambiente Linux (WSL2).
# Viene fatto per non avere le cartelle node_modules nei volumi diverse da quelle
# sull'host, in tal modo evitando di dover ri-creare ogni volta i container

version: "3.9"
services:
    # redis:
    #     image: redis
    #     networks:
    #         - backend
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        ports:
            - "5000:5000"
        networks:
            - backend
        volumes:
            - ./backend:/app
            # - backend-node_modules:/app/node_modules
        environment:
            - IP=0.0.0.0
            - PORT=5000
            # - REDIS_URL=redis://cache
            - NODE_ENV=development
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        networks:
            - backend
            - frontend
        volumes:
            - ./frontend:/app
            # - frontend-node_modules:/app/node_modules
        environment:
            - HOST=0.0.0.0
            - PORT=3000
            - NODE_ENV=development

networks:
    frontend: {}
    backend: {}
volumes:
    backend-node_modules: {}
    frontend-node_modules: {}
