# QUESTO DOCKER-COMPOSE È USATO SOLO PER IL DEBUGGING
# In produzione, le cartelle node_modules non vengono incluse neille immagini

# Ciò è fattibile in development in quanto si programma già in ambiente Linux (WSL2).
# Viene fatto per non avere le cartelle node_modules nei volumi diverse da quelle
# sull'host, in tal modo evitando di dover ri-creare ogni volta le immagini e i container

version: "3.9"
services:
    # DEBUG usato per caching, forse inutile
    # redis:
    #     image: redis
    #     networks:
    #         - backend
    mongodb:
        image: mongo:latest
        restart: always
        networks:
            - backend
        ports:
            # DEBUG le porte vengono pubblicate
            # In produzione viene fatto soltanto l'expose
            - 27017:27017
        volumes:
            - mongodb_data:/data/db
        logging:
            # Sopprimi output
            driver: "none"
    backend:
        depends_on:
            - mongodb
        build:
            context: ./backend
            # DEBUG usa Dockerfile di debug
            dockerfile: Dockerfile.dev
        ports:
            # DEBUG le porte vengono pubblicate
            # In produzione viene fatto soltanto l'expose
            - "5000:5000"
        networks:
            - backend
        volumes:
            - ./backend:/app
            # DEBUG in dev node_modules è incluso nell'immagine
            # - backend-node_modules:/app/node_modules
        environment:
            - IP=0.0.0.0
            - PORT=5000
            # - REDIS_URL=redis://redis
            # DEBUG viene usata la NODE_ENV development
            - NODE_ENV=development
            - MONGODB_URI=mongodb://mongodb:27017/occupa-lo-studente
            - AUTH_COOKIE_NAME=token
            # DEBUG viene usato un secret semplice
            - JWT_SECRET=fermi
            # DEBUG viene usato un secret semplice
            - COOKIE_SECRET=fermi
            # DEBUG viene usata pagina di localhost
            - SIGNUP_URL=http://localhost:3000/signup
            - LAST_PAGE_URL_COOKIE_NAME=lastpage
            - TEMP_AUTH_DATA_COOKIE_NAME=tempauthdata
            - EMAIL_SUFFIX=fermi.mo.it
    frontend:
        depends_on:
            - backend
        build:
            context: ./frontend
            # DEBUG usa Dockerfile di debug
            dockerfile: Dockerfile.dev
        ports:
            # DEBUG usa porta HTTP/HTTPS in produzione
            - "3000:3000"
        networks:
            - backend
            - frontend
        volumes:
            - ./frontend:/app
            # DEBUG in dev node_modules è incluso nell'immagine
            # - frontend-node_modules:/app/node_modules
        environment:
            - HOST=0.0.0.0
            - PORT=3000
            # DEBUG viene usata la NODE_ENV development
            - NODE_ENV=development

networks:
    frontend: {}
    backend: {}
volumes:
    # DEBUG in dev node_modules è incluso nell'immagine
    # backend-node_modules: {}
    # frontend-node_modules: {}
    mongodb_data: {}
